ARG BASE_IMAGE=nvidia/cudagl:10.0-devel-ubuntu18.04
FROM $BASE_IMAGE

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils

RUN python3 -m pip install --upgrade pip && \
    pip3 install setuptools wheel && \
    pip3 install colosseum

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash colosseum_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser colosseum_user sudo && \
	adduser colosseum_user audio && \
	adduser colosseum_user video

USER colosseum_user
WORKDIR /home/colosseum_user

RUN mkdir -p /home/colosseum_user/Documents/Colosseum
COPY settings.json /home/colosseum_user/Documents/Colosseum
#ADD Documents /home/colosseum_user/Documents

RUN sudo chown -R colosseum_user /home/colosseum_user
